/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XkabacAmbulanceWlList {
    }
}
declare global {
    interface HTMLXkabacAmbulanceWlListElement extends Components.XkabacAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXkabacAmbulanceWlListElement: {
        prototype: HTMLXkabacAmbulanceWlListElement;
        new (): HTMLXkabacAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xkabac-ambulance-wl-list": HTMLXkabacAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XkabacAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xkabac-ambulance-wl-list": XkabacAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xkabac-ambulance-wl-list": LocalJSX.XkabacAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXkabacAmbulanceWlListElement>;
        }
    }
}
